Display Coupon details feature1-core
csys-fresher-batch-2021/couponapp-core-nivethitha pull request #2
Opened 2021-06-02 11:23 UTC by Nivethitha98

2021-06-03 07:54 UTC, Nivethitha98 commented on src/main/java/in/nivethitha/dao/CouponDAO.java
> +
add printstacktrace

2021-06-03 07:55 UTC, Nivethitha98 commented on src/main/java/in/nivethitha/util/ConnectionUtil.java
> +		public static void close(ResultSet rs, PreparedStatement ps, Connection con) throws DBConnectionCloseException {
remove throws

2021-06-03 07:55 UTC, Nivethitha98 commented on src/main/java/in/nivethitha/util/ConnectionUtil.java
> +				rs.close();
add null check

2021-06-03 07:56 UTC, Nivethitha98 commented on src/main/java/in/nivethitha/util/ConnectionUtil.java
> +				throw new DBConnectionCloseException(e, "Unable to close connection");
avoid throwing exception when closing

2021-06-03 07:57 UTC, Nivethitha98 commented on src/main/java/in/nivethitha/util/ConnectionUtil.java
> +		private static String driverClass = "org.postgresql.Driver";
avoid hard coding db credentials use environment variables

2021-06-04 09:06 UTC, csys-fresher-batch-2021 commented on sql/create.sql
> +status varchar(10));
Add check constraint for status column e.g: 
CHECK ( status n ('OPEN','CLOSED'))

2021-06-04 09:09 UTC, csys-fresher-batch-2021 commented on src/main/java/in/nivethitha/model/CouponDetails.java
> +public class CouponDetails {
Rename class to "CouponDetail"

2021-06-04 09:10 UTC, csys-fresher-batch-2021 commented on src/main/java/in/nivethitha/model/CouponDetails.java
> +	private Date startDate;
Use LocalDate instead of date. LocalDate has more utility methods like isAfter, isBefore etc..

2021-06-04 09:12 UTC, csys-fresher-batch-2021 requested changes
I have added my review comments.

2021-06-05 03:12 UTC, csys-fresher-batch-2021 commented on sql/create.sql
> +values('flipkart','25','4500','2021-06-12','2021-06-20','OPEN');
Remove single quotes for numeric values like amount

2021-06-05 03:13 UTC, csys-fresher-batch-2021 commented on src/main/java/in/nivethitha/dao/CouponDAO.java
> +				LocalDate startDate = ((java.sql.Date) openDate).toLocalDate();
Remove typecasting. Access directly.
LocalDate startDate =openDate.toLocalDate();

2021-06-05 03:14 UTC, csys-fresher-batch-2021 commented on src/main/java/in/nivethitha/dao/CouponDAO.java
> +import java.util.Date;
Import java.sql.Date ( remove java.util.Date)

2021-06-05 03:15 UTC, csys-fresher-batch-2021 commented on src/main/java/in/nivethitha/service/DisplayCouponDetails.java
> +	public static void main(String[] args) {
Move main method to test/java folder.

2021-06-05 03:15 UTC, csys-fresher-batch-2021 requested changes
Added code review comments.

2021-06-05 16:23 UTC, Nivethitha98 commented on src/main/java/in/nivethitha/dao/CouponDAO.java
> +
added printstacktrace

2021-06-05 16:35 UTC, csys-fresher-batch-2021 approved these changes

2021-06-05 16:36 UTC, merged